MAIN_COLOUR = "#00008b"
ADD_COLOUR = "#87ceeb"

WINDOW_WIDTH = 1100
WINDOW_HEIGHT = 800

# Frame sizes (relative).
INPUT_PART_WIDTH = 0.15
INPUT_PART_HEIGHT = 0.40

BORDERS_PART = 0.05

DATA_PART_HEIGHT = 0.45
DATA_PART_WIDTH = 0.15

FIELD_PART_WIDTH = 0.65
FIELD_PART_HEIGHT = 0.9


FIELD_WIDTH = FIELD_PART_WIDTH * WINDOW_WIDTH
FIELD_HEIGHT = FIELD_PART_HEIGHT * WINDOW_HEIGHT


LINE_WIDTH = 3


FIELD_BORDER_PART = 0.05
